apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.1 (46dcb9181)
  creationTimestamp: null
  labels:
    io.kompose.service: slackfrontend
  name: slackfrontend
  namespace: default
spec:
  ports:
    - name: "888"
      port: 888
      targetPort: 3000
  selector:
    io.kompose.service: slackfrontend
status:
  loadBalancer: {}
